stages:
  - build
  - test
  - deploy

variables:
  PROJECT_DIR: "/var/www"
  BACKEND_DIR: "Todo-back-main"
  FRONTEND_DIR: "Todo-front-main"
  PYTHON_VERSION: "3.10"
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .cache/pip
    - ${BACKEND_DIR}/.cache

build_backend:
  stage: build
  tags:
    - docker
  script:
    - apt-get update && apt-get install -y python3-pip python3-venv
    - python3 -m pip install --upgrade pip
    - cd ${BACKEND_DIR}
    - pip install -r requirements.txt pytest pytest-django psycopg2-binary
    - python3 manage.py collectstatic --noinput
  artifacts:
    paths:
      - ${BACKEND_DIR}/
      - ${FRONTEND_DIR}/ 
    expire_in: 1 week

test_backend:
  stage: test
  needs: ["build_backend"]
  tags:
    - docker
  services:
    - name: postgres:14
      alias: postgres
  variables:
    DB_HOST: "localhost"
    DB_PORT: "5432"
    DB_NAME: "test_db"
    DB_USER: "postgres"
    DB_PASSWORD: "postgres"
  script:
    - apt-get update && apt-get install -y python3-pip
    - pip3 install --user xmlrunner
    - cd ${BACKEND_DIR}
    - mkdir -p test-reports
    - python3 -m xmlrunner discover -o test-reports/ -p "*tests*.py"
    - ls -la test-reports/
  artifacts:
    when: always
    reports:
      junit: ${BACKEND_DIR}/test-reports/*.xml
    expire_in: 1 week




deploy_staging:
  stage: deploy
  only:
    - br1
  environment:
    name: staging
    url: http://$DEPLOY_HOST:8081
  before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$DEPLOY_KEY" | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan $DEPLOY_HOST >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  script:
    - ineed error
    - echo "Deploying backend to staging..."
    - rsync -avz -e "ssh -o StrictHostKeyChecking=no" ${BACKEND_DIR}/ $DEPLOY_USER@$DEPLOY_HOST:$STAGING_DIR/backend/
    - ssh $DEPLOY_USER@$DEPLOY_HOST "
      cd ${STAGING_DIR}/backend &&
      source venv/bin/activate &&
      pip install -r requirements.txt &&
      gunicorn -b 0.0.0.0:8081 todoback.wsgi:application --daemon &&
      sudo systemctl restart nginx
      "

deploy_production:
  stage: deploy
  only:
    - master
  when: manual
  environment:
    name: production
    url: http://$DEPLOY_HOST
  script:
    - echo "Deploying to production..."
    - rsync -avz -e "ssh -o StrictHostKeyChecking=no" ${BACKEND_DIR}/ $DEPLOY_USER@$DEPLOY_HOST:${PRODUCTION_DIR}/backend/
    - ssh $DEPLOY_USER@$DEPLOY_HOST "
      cd ${PRODUCTION_DIR}/backend &&
      source venv/bin/activate &&
      pip install -r requirements.txt &&
      sudo systemctl restart todo.service &&
      sudo systemctl restart nginx
      "